server:
  port: 8080

eureka:
  client:
    #默认情况下注册到eureka server的服务是通过心跳来告知自己是UP还是DOWN，并不是通过spring-boot-actuator模块的/health端点来实现的
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${eureka-user.name}:${eureka-user.password}@${eureka-user.hostname}:${eureka-user.port}/eureka
  instance:
    #ip显示
    prefer-ip-address: true
    #自定义显示
    instance-id: ${spring.application.name}:${server.port}
    #元数据
    metadata-map:
      zone: ABC
      libowen: BBC
    #作为一个实例也包括定期心跳到注册表（通过客户端的serviceUrl），默认持续时间为30秒。在实例，服务器和客户端在其本地缓存中都具有相同的元数据（因此可能需要3个心跳）之前，客户端才能发现服务。您可以使用eureka.instance.leaseRenewalIntervalInSeconds更改期限，这将加快客户端连接到其他服务的过程。在生产中，最好坚持使用默认值，因为服务器内部有一些计算可以对租赁更新期进行假设
    #leaseRenewalIntervalInSeconds: 5

eureka-user:
  hostname: localhost
  port: 8761
  name: admin
  password: admin123

spring:
  application:
    name: microservice-provider-user-v1
    #name: microservice-provider-user-v1   zuul 正则匹配写法
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
  #在浏览器中开启控制台 localhost:8080/h2-console
  h2:
    console:
      enabled: true
      #path: h2-console

logging:
  level:
    root: debug
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinfer: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.libowen: DEBUG
